### ISSUE TITLE
Help posting a copy of our survey on our web site

### ISSUE THREAD

**Issue by selleck** [codeisland/candidate-questionnaire#1]
Hi everyone,

Today we released our survey to the three main Providence mayoral candidates.  It was sent via e-mail and also regular mail.  I would now like to tweet it out, especially since there is a firestorm in the twittersphere about open government due to the release of the election poll at 5pm.  

I don't want to tweet out a link to our actual survey, because then we'll get all of these dummy responses.  But I would like a web representation of the survey.  Here is a link to the Word version of the survey (including the intro letter and following FAQ):

https://drive.google.com/file/d/0B9q_Dz6FByMLcnhCX3R2eU1DNmM/edit?usp=sharing

Can someone get a nice looking web representation of this on our site?  Then we can tweet it out like crazy.

**Comment by ghost** [comment]
Long story short: No.

The existing site is severely limited in what it can do. I have a Wordpress
site in development, but we haven't changed the DNS settings to point to
that server.

Would you want to post it on RI Future? I could do that.

John Speck
401-369-2864 **NEW**

**Comment by selleck** [comment]
Thanks for the prompt response, John.

I'd love a writeup on RI Future once this is up and tweeted out.

Danny put the form up on our Github account with its own little page, so
maybe I can ask him if he can do something similar for the entire document,
and just removing the entry fields.  I'll reach out to him directly if he
isn't getting this.

Otherwise, I personally don't mind linking directly to the Word Doc link
that I provided below, but it won't appear as refined.

Thanks again and I'll circle up when more details are available.

Shawn

**Comment by nelsonri72** [comment]
@dannychapman

**Comment by jamesrhaley** [comment]
Hi everybody and John Speck

I would love to help with a plan.  If a discussion has taken place on what
I am asking I apologize for not paying enough attention.  Is the goal to
have this word press site be the home for Code Island projects or are
members suppose to host there work themselves.  If the goal is the first
one what can I do if anything to help?

With all of the different projects we have planned I feel we would have an
easier time designing our outcomes if we built them off of the foundation
that the word press site will have established.  For instance the word
press site already has css and javascript that our independent work might
clash with.

I will help with anything.  The questions I have is where is this site
going to be hosted and who are going to be the "web masters" for it?

Cheers,
James Haley

**Comment by joealba** [comment]
GitHub Pages instead of Wordpress, _pretty please_

**Comment by jamesrhaley** [comment]
Hi Joe,

Thank you for your response.  That sounds like a good idea.  Could you
possible share an example of what you are leaning toward.  It doesn't have
to be a Code for America.  It can be anything.

James

**Comment by ghost** [comment]
All,

For clarity, the WP site is to be the brigade's public-facing,
general-purpose resource. You know...a website! I agree with Joe that
projects should stay in GitHub.

Right now, the site is on my personal/consulting web hosting account. I
believe that the longterm plan is that the state will provide us with
hosting. The current version is in a sub-folder of my personal/non-existent
website. You can see it here: http://spekah.com/CodeIsland

In the short term, it will be in a root-level folder. The hang up at the
moment is that we need to change the domain's DNS settings to point to this
server.

Also, I am now the brigade's official "storyteller," which is a required
position from CfA mothership for all brigades. Thus, I am responsible for
all the content on the WP site. That said, I am more than happy to have
other, more knowledgable people work on the backend and the CSS.

I hope that helps clear up any confusion. Questions, concerns, suggestions?

John Speck
401-369-2864 **NEW**

**Comment by theryankelly** [comment]
I have a lot of input I need to share with the group on the topic. I am still at the CfA summit.  Expect an email/git issue with more info in comming days.

Quickly there are a few topics in this thread.  Home page and project pages. As we design a home we need to think about integrating current and future projects. I will lay out some goals and then we will work to make some awesome stuff.

We also have hosting now more on that later.

Ryan

**Comment by ghost** [comment]
I just sent out the tweet about the questionnaire. (Please RT!!!) Will post
to FB too. (Please Like and Share!!!)

Exclamation points!!!

John Speck
401-369-2864 **NEW**

**Comment by jamesrhaley** [comment]
Thank you for the clarification John

James
